import Foundation

/// Original LoopController adapter.
/// Produces a Clash/Stash-compatible YAML profile for Rocket Proxy.
/// The exporter emits configuration syntax only; it does not automate the
/// third-party application.
struct RocketProxyExporter {
    func export(_ profile: NetworkProfile) -> String {
        var lines: [String] = [
            "# LoopController export",
            "# Profile: \(profile.name)",
            "# Generated by LoopController",
            "",
            "mixed-port: 7890",
            "allow-lan: false",
            "mode: rule",
            "log-level: info",
            "",
            "proxies: []",
            "proxy-groups:",
            "  - name: LOOPCONTROLLER",
            "    type: select",
            "    proxies:",
            "      - DIRECT",
            "",
            "rules:"
        ]

        for route in profile.routes {
            let network = "\(route.destination)/\(route.prefixLength)"
            lines.append("  - IP-CIDR,\(network),DIRECT,no-resolve")
        }

        if profile.dns.enabled, !profile.dns.servers.isEmpty {
            lines += [
                "",
                "dns:",
                "  enable: true",
                "  enhanced-mode: redir-host",
                "  nameserver:"
            ]
            for server in profile.dns.servers {
                lines.append("    - \(server)")
            }
        } else {
            lines += [
                "",
                "dns:",
                "  enable: false"
            ]
        }

        if profile.blocking.enabled {
            lines += [
                "",
                "# Blocking requested by LoopController:",
                "# malware: \(profile.blocking.malware)",
                "# phishing: \(profile.blocking.phishing)",
                "# tracker: \(profile.blocking.tracker)",
                "# adult: \(profile.blocking.adult)",
                "# gambling: \(profile.blocking.gambling)",
                "# Add project-approved rule providers before enabling category blocking."
            ]
        }

        lines.append("  - MATCH,DIRECT")
        return lines.joined(separator: "\n") + "\n"
    }
}
