import Foundation

/// Explicit export targets supported by LoopController.
/// This layer creates configuration artifacts; it does not install, launch,
/// or silently modify third-party applications.
enum ApplicationConfigurationTarget: String, CaseIterable, Codable {
    case loopController = "loopcontroller"
    case surge
    case rocketProxy = "rocket-proxy"
    case wireGuard = "wireguard"
}

extension ConfigurationExportService {
    func exportToData(_ profile: NetworkProfile, target: ApplicationConfigurationTarget) throws -> ExportArtifact {
        switch target {
        case .loopController:
            return try export(profile, target: .loopController)
        case .surge:
            return try export(profile, target: .surge)
        case .rocketProxy:
            return try export(profile, target: .rocketProxy)
        case .wireGuard:
            return try WireGuardConfigurationExporter().export(profile)
        }
    }
}

struct WireGuardConfigurationExporter: ConfigurationExporter {
    let target: ConfigurationTarget = .loopController

    func export(_ profile: NetworkProfile) throws -> ExportArtifact {
        var lines = ["# Generated by LoopController", "[Interface]"]
        if !profile.dns.servers.isEmpty {
            lines.append("DNS = (profile.dns.servers.joined(separator: ", "))")
        }
        lines.append("")
        lines.append("[Peer]")
        lines.append("# Peer keys and endpoint are intentionally not invented.")
        lines.append("")
        guard let data = lines.joined(separator: "\n").data(using: .utf8) else {
            throw ExportError.encodingFailed
        }
        return ExportArtifact(
            target: .loopController,
            filename: "(safeExportName(profile.name)).wireguard.conf",
            mimeType: "text/plain",
            data: data,
            warnings: ["Peer PublicKey, Endpoint and AllowedIPs require explicit user-supplied values."]
        )
    }
}

private func safeExportName(_ value: String) -> String {
    let allowed = CharacterSet.alphanumerics.union(CharacterSet(charactersIn: "-_."))
    return value.unicodeScalars.map { allowed.contains($0) ? String($0) : "_" }.joined()
}
