import Foundation

/// Original LoopController adapter.
/// Generates a Surge profile from a NetworkProfile.
/// No third-party source code is copied into this file.
struct SurgeExporter {
    func export(_ profile: NetworkProfile) -> String {
        var lines: [String] = [
            "# LoopController export",
            "# Profile: \(profile.name)",
            "# Generated by LoopController",
            "",
            "[General]",
            "loglevel = notify"
        ]

        if profile.dns.enabled, !profile.dns.servers.isEmpty {
            lines.append("dns-server = \(profile.dns.servers.joined(separator: ", "))")
        }

        lines += [
            "",
            "[Rule]"
        ]

        for route in profile.routes {
            let type = route.destination.contains(":") ? "IP-CIDR6" : "IP-CIDR"
            lines.append("\(type),\(route.destination)/\(route.prefixLength),DIRECT,no-resolve")
        }

        if profile.blocking.enabled {
            lines.append("# Blocking requested: malware=\(profile.blocking.malware), phishing=\(profile.blocking.phishing), tracker=\(profile.blocking.tracker), adult=\(profile.blocking.adult), gambling=\(profile.blocking.gambling)")
            lines.append("# Add project-approved RULE-SET resources for these categories.")
        }

        lines.append("FINAL,DIRECT")
        return lines.joined(separator: "\n") + "\n"
    }
}
